spring:
  rabbitmq:
    addresses: 192.168.200.52:5672,192.168.200.104:5672,192.168.200.106:5672
    username: admin
    password: mysteel123
    publisher-confirms: true
    publisher-returns: true
